# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: false
repos:
# Clean notebook output (prevent committing of large output such as plots)
-   repo: local
    hooks:
    - id: clean-notebooks
      name: Clean notebooks
      language: system
      files: .*\.ipynb$
      entry: "conda run --name annotated_docs_env jupyter nbconvert --clear-output"
# General cleanup hooks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: check-added-large-files
    - id: check-shebang-scripts-are-executable
      exclude: Jenkinsfile
    - id: check-toml
    - id: detect-aws-credentials
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: fix-byte-order-marker
    - id: mixed-line-ending
    - id: trailing-whitespace
      exclude: ^logs/
    - id: name-tests-test
# Shellcheck .sh linter
-   repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.7.2
    hooks:
    -   id: shellcheck
        args: ["--severity=error"]
        files: '.*\.sh$'
# Make sure code is formatted according to standards
-   repo: local
    hooks:
    - id: code-formatting
      name: Run auto-code formatters
      pass_filenames: false
      language: system
      entry: "conda run --name annotated_docs_env tools/run_formatting.sh"
